#!/usr/bin/env bash

# Exit immediately on errors, treat unset variables as errors, and fail the
# script if any command in a pipeline fails.
set -euo pipefail

# Directory containing Terraform code.
#
# Can be overridden when running the script:
#   TF_DIR=terraform ./scripts/deploy.sh
TF_DIR="${TF_DIR:-terraform}"

# File created by the image build/push script.
#
# This file contains IMAGE_BASE, IMAGE_TAG, and IMAGE so the deploy script knows
# exactly which container image should be deployed to GKE.
IMAGE_FILE="${IMAGE_FILE:-.generated/image.env}"

# Directory containing Kubernetes manifest templates/source files.
K8S_DIR="${K8S_DIR:-k8s}"

# Directory where rendered Kubernetes manifests will be written.
#
# The deployment manifest is templated because it needs values like IMAGE,
# REDIS_HOST, and REDIS_PORT.
RENDER_DIR="${RENDER_DIR:-.generated/k8s}"

# Stop if the image metadata file does not exist.
#
# This prevents deploying without first building and pushing an image.
if [[ ! -f "${IMAGE_FILE}" ]]; then
  echo "ERROR: ${IMAGE_FILE} not found."
  echo "Run scripts/build-push-cloudbuild.sh or scripts/build-push.sh first."
  exit 1
fi

# Load IMAGE_BASE, IMAGE_TAG, and IMAGE from the generated image metadata file.
#
# This file is generated by the build script and should be trusted local output, not arbitrary user input.
#
# source executes the file in the current shell, so the variables become available to this deploy script.
#
# Security note: source runs whatever shell code is in the file. This is safe
# here because .generated/image.env is created by our own build script, not
# downloaded from an untrusted source or supplied by a user.
source "${IMAGE_FILE}"

# Read deployment values from Terraform outputs.
#
# Terraform owns the infrastructure, so the script gets the real project,
# cluster, bastion, and Redis connection details from Terraform state instead of hardcoding them here.
PROJECT_ID="$(terraform -chdir="${TF_DIR}" output -raw project_id)"
CLUSTER_NAME="$(terraform -chdir="${TF_DIR}" output -raw gke_cluster_name)"
CLUSTER_LOCATION="$(terraform -chdir="${TF_DIR}" output -raw gke_cluster_location)"
BASTION_NAME="$(terraform -chdir="${TF_DIR}" output -raw bastion_name)"
BASTION_ZONE="$(terraform -chdir="${TF_DIR}" output -raw bastion_zone)"
REDIS_HOST="$(terraform -chdir="${TF_DIR}" output -raw redis_host)"
REDIS_PORT="$(terraform -chdir="${TF_DIR}" output -raw redis_port)"

# Create the local render directory for generated Kubernetes manifests.
mkdir -p "${RENDER_DIR}"

# Copy static manifests into the render directory.
#
# These files do not need variable substitution for real-world resource names.
cp "${K8S_DIR}/namespace.yaml" "${RENDER_DIR}/namespace.yaml"
cp "${K8S_DIR}/backendconfig.yaml" "${RENDER_DIR}/backendconfig.yaml"
cp "${K8S_DIR}/service.yaml" "${RENDER_DIR}/service.yaml"
cp "${K8S_DIR}/ingress.yaml" "${RENDER_DIR}/ingress.yaml"

# Export variables needed by envsubst.
#
# envsubst only substitutes environment variables, so IMAGE, REDIS_HOST, and
# REDIS_PORT must be exported before rendering deployment.yaml.tpl.

# Shell variables are not automatically visible to child processes. export makes
# IMAGE, REDIS_HOST, and REDIS_PORT available to envsubst so it can replace
# placeholders in deployment.yaml.tpl.
export IMAGE REDIS_HOST REDIS_PORT

# Render the Kubernetes Deployment manifest from the template.
#
# The template contains placeholders such as ${IMAGE}, ${REDIS_HOST}, and
# ${REDIS_PORT}. envsubst replaces those placeholders with the exported values.
envsubst < "${K8S_DIR}/deployment.yaml.tpl" > "${RENDER_DIR}/deployment.yaml"

# We apply Kubernetes manifests from the bastion instead of the local machine.
#
# The GKE cluster has a private control plane, so kubectl access is expected to
# happen from the bastion, which has private network access to the cluster and
# has gcloud/kubectl installed by the startup script.

# Remote directory on the bastion where manifests will be extracted.
REMOTE_DIR="/tmp/demo-app-k8s"

# Remote tarball path on the bastion.
REMOTE_TARBALL="/tmp/demo-app-k8s.tar.gz"

# Local tarball path containing the rendered manifests.
LOCAL_TARBALL=".generated/demo-app-k8s.tar.gz"

echo "Checking rendered manifests locally..."
ls -la "${RENDER_DIR}"

echo "Creating manifest archive..."

# Package the rendered manifests into a tar.gz archive.
#
# This is more reliable than recursively copying a directory with gcloud scp,
# especially from Windows/Git Bash environments.


# -C "${RENDER_DIR}" changes into the render directory first.
# -c creates a new archive.
# -z compresses it with gzip.
# -f "${LOCAL_TARBALL}" writes the archive to that file.
# . means "archive the contents of the current directory", which is RENDER_DIR
# because of -C.
tar -C "${RENDER_DIR}" -czf "${LOCAL_TARBALL}" .

echo "Preparing remote manifest directory on bastion..."

# Connect to the private bastion through IAP and prepare a clean remote directory.
#
# --tunnel-through-iap lets us SSH to the bastion even though it has no public IP.
gcloud compute ssh "${BASTION_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${BASTION_ZONE}" \
  --tunnel-through-iap \
  --command "rm -rf ${REMOTE_DIR} ${REMOTE_TARBALL} && mkdir -p ${REMOTE_DIR}"

echo "Copying manifest archive to bastion..."

# Copy the manifest archive to the bastion through IAP.
gcloud compute scp "${LOCAL_TARBALL}" "${BASTION_NAME}:${REMOTE_TARBALL}" \
  --project "${PROJECT_ID}" \
  --zone "${BASTION_ZONE}" \
  --tunnel-through-iap

echo "Extracting manifests on bastion..."

# Extract the manifest archive on the bastion and list the extracted files so we can verify what will be applied.
#
# -x extracts files.
# -z tells tar the archive is gzip-compressed.
# -f selects the tarball file to extract.
# -C chooses the destination directory.
# && lists the extracted files only if tar extraction succeeds.
gcloud compute ssh "${BASTION_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${BASTION_ZONE}" \
  --tunnel-through-iap \
  --command "tar -xzf ${REMOTE_TARBALL} -C ${REMOTE_DIR} && ls -la ${REMOTE_DIR}"

echo "Applying Kubernetes manifests from bastion..."

# SSH to the bastion and run the Kubernetes deployment steps from there.
#
# Local variables like PROJECT_ID and CLUSTER_NAME are expanded before the command is sent to the bastion.
#
# Remote shell expressions that should run on the bastion, such as $(kubectl ...), are escaped as \$(...) so they are not evaluated by the local shell first.
gcloud compute ssh "${BASTION_NAME}" \
  --project "${PROJECT_ID}" \
  --zone "${BASTION_ZONE}" \
  --tunnel-through-iap \
  --command "
    set -euo pipefail

    # Set the active gcloud project on the bastion for the commands below.
    gcloud config set project ${PROJECT_ID}

    # Get Kubernetes credentials for the private GKE cluster.
    #
    # --internal-ip forces gcloud/kubectl to use the private control plane endpoint, which is reachable from the bastion.
    # It tells gcloud to configure kubectl to use the private/internal Kubernetes control plane endpoint.
    gcloud container clusters get-credentials ${CLUSTER_NAME} \
      --region ${CLUSTER_LOCATION} \
      --project ${PROJECT_ID} \
      --internal-ip

    # Apply manifests in dependency order:
    # namespace first, then namespace-scoped resources, then service/ingress.

    # Apply manifests in an order that avoids dependency timing issues.
    #
    # Namespace must exist before namespace-scoped resources.
    # BackendConfig should exist before the Service references it.
    # Service should exist before Ingress points traffic to it.
    #
    # kubectl can apply a whole directory, but explicit ordering makes this script
    # easier to understand and reduces temporary controller warnings.
    kubectl apply -f ${REMOTE_DIR}/namespace.yaml
    kubectl apply -f ${REMOTE_DIR}/backendconfig.yaml
    kubectl apply -f ${REMOTE_DIR}/deployment.yaml
    kubectl apply -f ${REMOTE_DIR}/service.yaml
    kubectl apply -f ${REMOTE_DIR}/ingress.yaml

    # Wait for the Deployment rollout to complete.
    #
    # If the rollout fails or times out, print useful diagnostics before exiting.
    # ! Means negate the command; if rollout status fails, the negation makes the if condition true and the script prints diagnostics.
    # --timeout=300s is a kubectl flag, not a Bash feature. It tells kubectl to wait up to 300 seconds, which is 5 minutes.

    if ! kubectl -n demo-app rollout status deployment/demo-app --timeout=300s; then
      echo 'Rollout did not complete. Showing diagnostics...'

      # Show Pod placement, node assignment, and status.
      # -o wide shows the extra details and other columns that are hidden by default.
      kubectl -n demo-app get pods -o wide

      # Show recent namespace events, which often explain scheduling, image pull, probe, or load balancer issues.
      #
      # readiness probe: decides whether the Pod is ready to receive traffic
      # liveness probe: decides whether the container should be restarted
      # startup probe: gives slow-starting apps extra time before liveness checks begin

      kubectl -n demo-app get events --sort-by=.lastTimestamp | tail -40

      # Show Deployment details, including replica status and recent conditions.
      kubectl -n demo-app describe deployment demo-app

      echo 'Showing pod logs...'

      # Print current and previous logs for each app Pod.
      #
      # Previous logs are useful when a container is restarting because the
      # current container may not contain the crash output anymore.
      #
      # show logs from the previous crashed/restarted container instance.
      # This matters when a Pod is in CrashLoopBackOff. The container may have crashed and restarted, so the current logs might not show the original crash. --previous often shows the real error.

      # -l app=demo-app filters to Pods with the label app=demo-app, which is set in the Deployment manifest.
      # -o jsonpath='{.items[*].metadata.name}' outputs only the Pod names, which are then iterated over in the for loop.
      # The semicolon before do is needed because do is on the same line.
      for pod in \$(kubectl -n demo-app get pods -l app=demo-app -o jsonpath='{.items[*].metadata.name}'); do
        echo '===== Logs for \$pod ====='

        # The || true means: this logs command fails, keep going. That is useful because --previous fails when there is no previous crashed container.
        kubectl -n demo-app logs \"\$pod\" --all-containers=true --tail=100 || true

        echo '===== Previous logs for \$pod ====='
        kubectl -n demo-app logs \"\$pod\" --all-containers=true --previous --tail=100 || true
      done

      exit 1
    fi

    # Show the final deployed resources.
    # Deployment creates Pods. Service gives those Pods a stable internal endpoint. Ingress connects the external load balancer to the Service
    kubectl -n demo-app get pods,svc,ingress
  "